image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install 

build_job:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script: [cd reddit]
  script:
    - docker build -t myimage .

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb 

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

branch review:
  image: python:latest
  stage: review
  before_script: []
  script:
    - pip3 install awscli 
    - aws s3 ls
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - sudo apt-get update
    - ./script.sh
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/ 
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/ 
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
