version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: sigorilla/ui:3.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    image: sigorilla/post:2.0
    networks:
      - reddit
  comment:
    image: sigorilla/comment:2.0
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
